dir: internal/mocks/repository
filename: mocks.go
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/4JesusApps/prayertexter/internal/messaging:
    config:
      dir: internal/mocks/messaging
      filename: mocks.go
    interfaces:
      MessageSender: {}
  github.com/4JesusApps/prayertexter/internal/repository:
    interfaces:
      BlockedPhonesRepository: {}
      DDBClient: {}
      IntercessorPhonesRepository: {}
      MemberRepository: {}
      PrayerRepository: {}
