Transform: AWS::Serverless-2016-10-31

Parameters:
  # The end user messaging SMS pool needs to be set here manually. This needs to be created separately and is managed
  # outside of cloudformation.
  SMSPhonePoolArn:
    Type: String
    Default: arn:aws:sms-voice:us-west-1:681271545794:pool/pool-34c6fe4aaf88416abe070959a2241a8b

Globals:
  Function:
    Timeout: 60
    MemorySize: 128
    Tracing: Active
    Environment:
      Variables:
        # Env variables need to match specific format. See prayertexter config package for details.
        PRAY_CONF_AWS_DB_PRAYER_ACTIVETABLE: !Ref ActivePrayer
        PRAY_CONF_AWS_DB_INTERCESSORPHONES_TABLE: !Ref General
        PRAY_CONF_AWS_DB_STATETRACKER_TABLE: !Ref General
        PRAY_CONF_AWS_DB_MEMBER_TABLE: !Ref Member
        PRAY_CONF_AWS_DB_PRAYER_QUEUETABLE: !Ref QueuedPrayer
        PRAY_CONF_AWS_SMS_PHONEPOOL: !Ref SMSPhonePoolArn

Resources:
  # Dynamodb tables
  ActivePrayer:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: IntercessorPhone
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: IntercessorPhone
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  General:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Key
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: Key
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  Member:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Phone
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: Phone
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  QueuedPrayer:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: IntercessorPhone
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: IntercessorPhone
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  # SNS topic that triggers PrayerTexter lambda function
  PrayerTexterMainTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: prayertexter-main-trigger

  # Log group for SMS delivery events
  SMSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: prayertexter-sms
      RetentionInDays: 30
      Tags:
        - Key: prayertexter
          Value: ""

  # Policy that allows sending logs to cloudwatch log group
  SMSVoiceLogPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: send-cloudwatch-logs-log-group-prayertexter-sms
      Path: /
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:DescribeLogStreams
              - logs:PutLogEvents
            Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:prayertexter-sms:*

  # Role that binds SMS to cloudwatch log group policy
  SMSVoiceLogRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: end-user-messaging-send-cloudwatch-logs
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sms-voice.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
              ArnLike:
                aws:SourceArn: !Sub arn:aws:sms-voice:${AWS::Region}:${AWS::AccountId}:configuration-set/prayertexter
      ManagedPolicyArns:
        - !Ref SMSVoiceLogPolicy

  # Main lambda function
  PrayerTexter:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      Description: !Sub "Stack ${AWS::StackName} Function PrayerTexter"
      CodeUri: cmd/prayertexter/apigateway-test/
      Handler: bootstrap
      Runtime: provided.al2023
      Policies:
        # Grants lambda function access to dynamodb tables
        - DynamoDBCrudPolicy:
            TableName: !Ref ActivePrayer
        - DynamoDBCrudPolicy:
            TableName: !Ref General
        - DynamoDBCrudPolicy:
            TableName: !Ref Member
        - DynamoDBCrudPolicy:
            TableName: !Ref QueuedPrayer
        # Grants lambda function access to send SMS
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sms-voice:SendTextMessage
              Resource: !Ref SMSPhonePoolArn
      Events:
        SNSTriggerTopic:
          Type: SNS
          Properties:
            Topic: !Ref PrayerTexterMainTopic

  # Log group for main lambda function
  PrayerTexterLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${PrayerTexter}

Outputs:
  PrayerTexterFunctionArn:
    Description: ARN of the PrayerTexter function
    Value: !GetAtt PrayerTexter.Arn

  MainTopicArn:
    Description: SNS Topic ARN for main messages
    Value: !Ref PrayerTexterMainTopic