// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/4JesusApps/prayertexter/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockPrayerRepository is an autogenerated mock type for the PrayerRepository type
type MockPrayerRepository struct {
	mock.Mock
}

type MockPrayerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrayerRepository) EXPECT() *MockPrayerRepository_Expecter {
	return &MockPrayerRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, key, queued
func (_m *MockPrayerRepository) Delete(ctx context.Context, key string, queued bool) error {
	ret := _m.Called(ctx, key, queued)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, key, queued)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPrayerRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPrayerRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - queued bool
func (_e *MockPrayerRepository_Expecter) Delete(ctx interface{}, key interface{}, queued interface{}) *MockPrayerRepository_Delete_Call {
	return &MockPrayerRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, key, queued)}
}

func (_c *MockPrayerRepository_Delete_Call) Run(run func(ctx context.Context, key string, queued bool)) *MockPrayerRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockPrayerRepository_Delete_Call) Return(_a0 error) *MockPrayerRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPrayerRepository_Delete_Call) RunAndReturn(run func(context.Context, string, bool) error) *MockPrayerRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, phone
func (_m *MockPrayerRepository) Exists(ctx context.Context, phone string) (bool, error) {
	ret := _m.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, phone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, phone)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPrayerRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockPrayerRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
func (_e *MockPrayerRepository_Expecter) Exists(ctx interface{}, phone interface{}) *MockPrayerRepository_Exists_Call {
	return &MockPrayerRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, phone)}
}

func (_c *MockPrayerRepository_Exists_Call) Run(run func(ctx context.Context, phone string)) *MockPrayerRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPrayerRepository_Exists_Call) Return(_a0 bool, _a1 error) *MockPrayerRepository_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPrayerRepository_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockPrayerRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key, queued
func (_m *MockPrayerRepository) Get(ctx context.Context, key string, queued bool) (*domain.Prayer, error) {
	ret := _m.Called(ctx, key, queued)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Prayer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (*domain.Prayer, error)); ok {
		return rf(ctx, key, queued)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) *domain.Prayer); ok {
		r0 = rf(ctx, key, queued)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Prayer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, key, queued)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPrayerRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPrayerRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - queued bool
func (_e *MockPrayerRepository_Expecter) Get(ctx interface{}, key interface{}, queued interface{}) *MockPrayerRepository_Get_Call {
	return &MockPrayerRepository_Get_Call{Call: _e.mock.On("Get", ctx, key, queued)}
}

func (_c *MockPrayerRepository_Get_Call) Run(run func(ctx context.Context, key string, queued bool)) *MockPrayerRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockPrayerRepository_Get_Call) Return(_a0 *domain.Prayer, _a1 error) *MockPrayerRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPrayerRepository_Get_Call) RunAndReturn(run func(context.Context, string, bool) (*domain.Prayer, error)) *MockPrayerRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx, queued
func (_m *MockPrayerRepository) GetAll(ctx context.Context, queued bool) ([]domain.Prayer, error) {
	ret := _m.Called(ctx, queued)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Prayer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bool) ([]domain.Prayer, error)); ok {
		return rf(ctx, queued)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bool) []domain.Prayer); ok {
		r0 = rf(ctx, queued)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Prayer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = rf(ctx, queued)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPrayerRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockPrayerRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - queued bool
func (_e *MockPrayerRepository_Expecter) GetAll(ctx interface{}, queued interface{}) *MockPrayerRepository_GetAll_Call {
	return &MockPrayerRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx, queued)}
}

func (_c *MockPrayerRepository_GetAll_Call) Run(run func(ctx context.Context, queued bool)) *MockPrayerRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bool))
	})
	return _c
}

func (_c *MockPrayerRepository_GetAll_Call) Return(_a0 []domain.Prayer, _a1 error) *MockPrayerRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPrayerRepository_GetAll_Call) RunAndReturn(run func(context.Context, bool) ([]domain.Prayer, error)) *MockPrayerRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, prayer, queued
func (_m *MockPrayerRepository) Save(ctx context.Context, prayer *domain.Prayer, queued bool) error {
	ret := _m.Called(ctx, prayer, queued)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Prayer, bool) error); ok {
		r0 = rf(ctx, prayer, queued)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPrayerRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockPrayerRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - prayer *domain.Prayer
//   - queued bool
func (_e *MockPrayerRepository_Expecter) Save(ctx interface{}, prayer interface{}, queued interface{}) *MockPrayerRepository_Save_Call {
	return &MockPrayerRepository_Save_Call{Call: _e.mock.On("Save", ctx, prayer, queued)}
}

func (_c *MockPrayerRepository_Save_Call) Run(run func(ctx context.Context, prayer *domain.Prayer, queued bool)) *MockPrayerRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Prayer), args[2].(bool))
	})
	return _c
}

func (_c *MockPrayerRepository_Save_Call) Return(_a0 error) *MockPrayerRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPrayerRepository_Save_Call) RunAndReturn(run func(context.Context, *domain.Prayer, bool) error) *MockPrayerRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPrayerRepository creates a new instance of MockPrayerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrayerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrayerRepository {
	mock := &MockPrayerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
