// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/4JesusApps/prayertexter/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockMemberRepository is an autogenerated mock type for the MemberRepository type
type MockMemberRepository struct {
	mock.Mock
}

type MockMemberRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMemberRepository) EXPECT() *MockMemberRepository_Expecter {
	return &MockMemberRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, phone
func (_m *MockMemberRepository) Delete(ctx context.Context, phone string) error {
	ret := _m.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, phone)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMemberRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMemberRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
func (_e *MockMemberRepository_Expecter) Delete(ctx interface{}, phone interface{}) *MockMemberRepository_Delete_Call {
	return &MockMemberRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, phone)}
}

func (_c *MockMemberRepository_Delete_Call) Run(run func(ctx context.Context, phone string)) *MockMemberRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMemberRepository_Delete_Call) Return(_a0 error) *MockMemberRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMemberRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockMemberRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, phone
func (_m *MockMemberRepository) Exists(ctx context.Context, phone string) (bool, error) {
	ret := _m.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, phone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, phone)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockMemberRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
func (_e *MockMemberRepository_Expecter) Exists(ctx interface{}, phone interface{}) *MockMemberRepository_Exists_Call {
	return &MockMemberRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, phone)}
}

func (_c *MockMemberRepository_Exists_Call) Run(run func(ctx context.Context, phone string)) *MockMemberRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMemberRepository_Exists_Call) Return(_a0 bool, _a1 error) *MockMemberRepository_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberRepository_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockMemberRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, phone
func (_m *MockMemberRepository) Get(ctx context.Context, phone string) (*domain.Member, error) {
	ret := _m.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Member, error)); ok {
		return rf(ctx, phone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Member); ok {
		r0 = rf(ctx, phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Member)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemberRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMemberRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
func (_e *MockMemberRepository_Expecter) Get(ctx interface{}, phone interface{}) *MockMemberRepository_Get_Call {
	return &MockMemberRepository_Get_Call{Call: _e.mock.On("Get", ctx, phone)}
}

func (_c *MockMemberRepository_Get_Call) Run(run func(ctx context.Context, phone string)) *MockMemberRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMemberRepository_Get_Call) Return(_a0 *domain.Member, _a1 error) *MockMemberRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemberRepository_Get_Call) RunAndReturn(run func(context.Context, string) (*domain.Member, error)) *MockMemberRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, member
func (_m *MockMemberRepository) Save(ctx context.Context, member *domain.Member) error {
	ret := _m.Called(ctx, member)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Member) error); ok {
		r0 = rf(ctx, member)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMemberRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockMemberRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - member *domain.Member
func (_e *MockMemberRepository_Expecter) Save(ctx interface{}, member interface{}) *MockMemberRepository_Save_Call {
	return &MockMemberRepository_Save_Call{Call: _e.mock.On("Save", ctx, member)}
}

func (_c *MockMemberRepository_Save_Call) Run(run func(ctx context.Context, member *domain.Member)) *MockMemberRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Member))
	})
	return _c
}

func (_c *MockMemberRepository_Save_Call) Return(_a0 error) *MockMemberRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMemberRepository_Save_Call) RunAndReturn(run func(context.Context, *domain.Member) error) *MockMemberRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMemberRepository creates a new instance of MockMemberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMemberRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMemberRepository {
	mock := &MockMemberRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
