// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/4JesusApps/prayertexter/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockIntercessorPhonesRepository is an autogenerated mock type for the IntercessorPhonesRepository type
type MockIntercessorPhonesRepository struct {
	mock.Mock
}

type MockIntercessorPhonesRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIntercessorPhonesRepository) EXPECT() *MockIntercessorPhonesRepository_Expecter {
	return &MockIntercessorPhonesRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx
func (_m *MockIntercessorPhonesRepository) Get(ctx context.Context) (*domain.IntercessorPhones, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.IntercessorPhones
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.IntercessorPhones, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.IntercessorPhones); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.IntercessorPhones)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIntercessorPhonesRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIntercessorPhonesRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIntercessorPhonesRepository_Expecter) Get(ctx interface{}) *MockIntercessorPhonesRepository_Get_Call {
	return &MockIntercessorPhonesRepository_Get_Call{Call: _e.mock.On("Get", ctx)}
}

func (_c *MockIntercessorPhonesRepository_Get_Call) Run(run func(ctx context.Context)) *MockIntercessorPhonesRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIntercessorPhonesRepository_Get_Call) Return(_a0 *domain.IntercessorPhones, _a1 error) *MockIntercessorPhonesRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIntercessorPhonesRepository_Get_Call) RunAndReturn(run func(context.Context) (*domain.IntercessorPhones, error)) *MockIntercessorPhonesRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, phones
func (_m *MockIntercessorPhonesRepository) Save(ctx context.Context, phones *domain.IntercessorPhones) error {
	ret := _m.Called(ctx, phones)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.IntercessorPhones) error); ok {
		r0 = rf(ctx, phones)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIntercessorPhonesRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockIntercessorPhonesRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - phones *domain.IntercessorPhones
func (_e *MockIntercessorPhonesRepository_Expecter) Save(ctx interface{}, phones interface{}) *MockIntercessorPhonesRepository_Save_Call {
	return &MockIntercessorPhonesRepository_Save_Call{Call: _e.mock.On("Save", ctx, phones)}
}

func (_c *MockIntercessorPhonesRepository_Save_Call) Run(run func(ctx context.Context, phones *domain.IntercessorPhones)) *MockIntercessorPhonesRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.IntercessorPhones))
	})
	return _c
}

func (_c *MockIntercessorPhonesRepository_Save_Call) Return(_a0 error) *MockIntercessorPhonesRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIntercessorPhonesRepository_Save_Call) RunAndReturn(run func(context.Context, *domain.IntercessorPhones) error) *MockIntercessorPhonesRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIntercessorPhonesRepository creates a new instance of MockIntercessorPhonesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIntercessorPhonesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIntercessorPhonesRepository {
	mock := &MockIntercessorPhonesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
