// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/4JesusApps/prayertexter/internal/domain"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDDBClient creates a new instance of MockDDBClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDDBClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDDBClient {
	mock := &MockDDBClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDDBClient is an autogenerated mock type for the DDBClient type
type MockDDBClient struct {
	mock.Mock
}

type MockDDBClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDDBClient) EXPECT() *MockDDBClient_Expecter {
	return &MockDDBClient_Expecter{mock: &_m.Mock}
}

// DeleteItem provides a mock function for the type MockDDBClient
func (_mock *MockDDBClient) DeleteItem(ctx context.Context, input *dynamodb.DeleteItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.DeleteItemOutput, error) {
	// func(*dynamodb.Options)
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, input)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItem")
	}

	var r0 *dynamodb.DeleteItemOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.DeleteItemInput, ...func(*dynamodb.Options)) (*dynamodb.DeleteItemOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.DeleteItemInput, ...func(*dynamodb.Options)) *dynamodb.DeleteItemOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.DeleteItemOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.DeleteItemInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDDBClient_DeleteItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItem'
type MockDDBClient_DeleteItem_Call struct {
	*mock.Call
}

// DeleteItem is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.DeleteItemInput
//   - opts ...func(*dynamodb.Options)
func (_e *MockDDBClient_Expecter) DeleteItem(ctx interface{}, input interface{}, opts ...interface{}) *MockDDBClient_DeleteItem_Call {
	return &MockDDBClient_DeleteItem_Call{Call: _e.mock.On("DeleteItem",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *MockDDBClient_DeleteItem_Call) Run(run func(ctx context.Context, input *dynamodb.DeleteItemInput, opts ...func(*dynamodb.Options))) *MockDDBClient_DeleteItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.DeleteItemInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.DeleteItemInput)
		}
		var arg2 []func(*dynamodb.Options)
		variadicArgs := make([]func(*dynamodb.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*dynamodb.Options))
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockDDBClient_DeleteItem_Call) Return(deleteItemOutput *dynamodb.DeleteItemOutput, err error) *MockDDBClient_DeleteItem_Call {
	_c.Call.Return(deleteItemOutput, err)
	return _c
}

func (_c *MockDDBClient_DeleteItem_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.DeleteItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.DeleteItemOutput, error)) *MockDDBClient_DeleteItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetItem provides a mock function for the type MockDDBClient
func (_mock *MockDDBClient) GetItem(ctx context.Context, input *dynamodb.GetItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.GetItemOutput, error) {
	// func(*dynamodb.Options)
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, input)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetItem")
	}

	var r0 *dynamodb.GetItemOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.GetItemInput, ...func(*dynamodb.Options)) (*dynamodb.GetItemOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.GetItemInput, ...func(*dynamodb.Options)) *dynamodb.GetItemOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.GetItemOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.GetItemInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDDBClient_GetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItem'
type MockDDBClient_GetItem_Call struct {
	*mock.Call
}

// GetItem is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.GetItemInput
//   - opts ...func(*dynamodb.Options)
func (_e *MockDDBClient_Expecter) GetItem(ctx interface{}, input interface{}, opts ...interface{}) *MockDDBClient_GetItem_Call {
	return &MockDDBClient_GetItem_Call{Call: _e.mock.On("GetItem",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *MockDDBClient_GetItem_Call) Run(run func(ctx context.Context, input *dynamodb.GetItemInput, opts ...func(*dynamodb.Options))) *MockDDBClient_GetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.GetItemInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.GetItemInput)
		}
		var arg2 []func(*dynamodb.Options)
		variadicArgs := make([]func(*dynamodb.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*dynamodb.Options))
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockDDBClient_GetItem_Call) Return(getItemOutput *dynamodb.GetItemOutput, err error) *MockDDBClient_GetItem_Call {
	_c.Call.Return(getItemOutput, err)
	return _c
}

func (_c *MockDDBClient_GetItem_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.GetItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.GetItemOutput, error)) *MockDDBClient_GetItem_Call {
	_c.Call.Return(run)
	return _c
}

// PutItem provides a mock function for the type MockDDBClient
func (_mock *MockDDBClient) PutItem(ctx context.Context, input *dynamodb.PutItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.PutItemOutput, error) {
	// func(*dynamodb.Options)
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, input)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PutItem")
	}

	var r0 *dynamodb.PutItemOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.PutItemInput, ...func(*dynamodb.Options)) (*dynamodb.PutItemOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.PutItemInput, ...func(*dynamodb.Options)) *dynamodb.PutItemOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.PutItemOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.PutItemInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDDBClient_PutItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutItem'
type MockDDBClient_PutItem_Call struct {
	*mock.Call
}

// PutItem is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.PutItemInput
//   - opts ...func(*dynamodb.Options)
func (_e *MockDDBClient_Expecter) PutItem(ctx interface{}, input interface{}, opts ...interface{}) *MockDDBClient_PutItem_Call {
	return &MockDDBClient_PutItem_Call{Call: _e.mock.On("PutItem",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *MockDDBClient_PutItem_Call) Run(run func(ctx context.Context, input *dynamodb.PutItemInput, opts ...func(*dynamodb.Options))) *MockDDBClient_PutItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.PutItemInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.PutItemInput)
		}
		var arg2 []func(*dynamodb.Options)
		variadicArgs := make([]func(*dynamodb.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*dynamodb.Options))
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockDDBClient_PutItem_Call) Return(putItemOutput *dynamodb.PutItemOutput, err error) *MockDDBClient_PutItem_Call {
	_c.Call.Return(putItemOutput, err)
	return _c
}

func (_c *MockDDBClient_PutItem_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.PutItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.PutItemOutput, error)) *MockDDBClient_PutItem_Call {
	_c.Call.Return(run)
	return _c
}

// Scan provides a mock function for the type MockDDBClient
func (_mock *MockDDBClient) Scan(ctx context.Context, params *dynamodb.ScanInput, optFns ...func(*dynamodb.Options)) (*dynamodb.ScanOutput, error) {
	// func(*dynamodb.Options)
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 *dynamodb.ScanOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.ScanInput, ...func(*dynamodb.Options)) (*dynamodb.ScanOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.ScanInput, ...func(*dynamodb.Options)) *dynamodb.ScanOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.ScanOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.ScanInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDDBClient_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockDDBClient_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - ctx context.Context
//   - params *dynamodb.ScanInput
//   - optFns ...func(*dynamodb.Options)
func (_e *MockDDBClient_Expecter) Scan(ctx interface{}, params interface{}, optFns ...interface{}) *MockDDBClient_Scan_Call {
	return &MockDDBClient_Scan_Call{Call: _e.mock.On("Scan",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockDDBClient_Scan_Call) Run(run func(ctx context.Context, params *dynamodb.ScanInput, optFns ...func(*dynamodb.Options))) *MockDDBClient_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.ScanInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.ScanInput)
		}
		var arg2 []func(*dynamodb.Options)
		variadicArgs := make([]func(*dynamodb.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*dynamodb.Options))
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockDDBClient_Scan_Call) Return(scanOutput *dynamodb.ScanOutput, err error) *MockDDBClient_Scan_Call {
	_c.Call.Return(scanOutput, err)
	return _c
}

func (_c *MockDDBClient_Scan_Call) RunAndReturn(run func(ctx context.Context, params *dynamodb.ScanInput, optFns ...func(*dynamodb.Options)) (*dynamodb.ScanOutput, error)) *MockDDBClient_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMemberRepository creates a new instance of MockMemberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMemberRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMemberRepository {
	mock := &MockMemberRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMemberRepository is an autogenerated mock type for the MemberRepository type
type MockMemberRepository struct {
	mock.Mock
}

type MockMemberRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMemberRepository) EXPECT() *MockMemberRepository_Expecter {
	return &MockMemberRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockMemberRepository
func (_mock *MockMemberRepository) Delete(ctx context.Context, phone string) error {
	ret := _mock.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, phone)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMemberRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMemberRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
func (_e *MockMemberRepository_Expecter) Delete(ctx interface{}, phone interface{}) *MockMemberRepository_Delete_Call {
	return &MockMemberRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, phone)}
}

func (_c *MockMemberRepository_Delete_Call) Run(run func(ctx context.Context, phone string)) *MockMemberRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMemberRepository_Delete_Call) Return(err error) *MockMemberRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMemberRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, phone string) error) *MockMemberRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockMemberRepository
func (_mock *MockMemberRepository) Exists(ctx context.Context, phone string) (bool, error) {
	ret := _mock.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, phone)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, phone)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, phone)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMemberRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockMemberRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
func (_e *MockMemberRepository_Expecter) Exists(ctx interface{}, phone interface{}) *MockMemberRepository_Exists_Call {
	return &MockMemberRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, phone)}
}

func (_c *MockMemberRepository_Exists_Call) Run(run func(ctx context.Context, phone string)) *MockMemberRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMemberRepository_Exists_Call) Return(b bool, err error) *MockMemberRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockMemberRepository_Exists_Call) RunAndReturn(run func(ctx context.Context, phone string) (bool, error)) *MockMemberRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockMemberRepository
func (_mock *MockMemberRepository) Get(ctx context.Context, phone string) (*domain.Member, error) {
	ret := _mock.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Member
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Member, error)); ok {
		return returnFunc(ctx, phone)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Member); ok {
		r0 = returnFunc(ctx, phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Member)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, phone)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMemberRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMemberRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
func (_e *MockMemberRepository_Expecter) Get(ctx interface{}, phone interface{}) *MockMemberRepository_Get_Call {
	return &MockMemberRepository_Get_Call{Call: _e.mock.On("Get", ctx, phone)}
}

func (_c *MockMemberRepository_Get_Call) Run(run func(ctx context.Context, phone string)) *MockMemberRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMemberRepository_Get_Call) Return(member *domain.Member, err error) *MockMemberRepository_Get_Call {
	_c.Call.Return(member, err)
	return _c
}

func (_c *MockMemberRepository_Get_Call) RunAndReturn(run func(ctx context.Context, phone string) (*domain.Member, error)) *MockMemberRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockMemberRepository
func (_mock *MockMemberRepository) Save(ctx context.Context, member *domain.Member) error {
	ret := _mock.Called(ctx, member)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Member) error); ok {
		r0 = returnFunc(ctx, member)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMemberRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockMemberRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - member *domain.Member
func (_e *MockMemberRepository_Expecter) Save(ctx interface{}, member interface{}) *MockMemberRepository_Save_Call {
	return &MockMemberRepository_Save_Call{Call: _e.mock.On("Save", ctx, member)}
}

func (_c *MockMemberRepository_Save_Call) Run(run func(ctx context.Context, member *domain.Member)) *MockMemberRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Member
		if args[1] != nil {
			arg1 = args[1].(*domain.Member)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMemberRepository_Save_Call) Return(err error) *MockMemberRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMemberRepository_Save_Call) RunAndReturn(run func(ctx context.Context, member *domain.Member) error) *MockMemberRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBlockedPhonesRepository creates a new instance of MockBlockedPhonesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlockedPhonesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlockedPhonesRepository {
	mock := &MockBlockedPhonesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlockedPhonesRepository is an autogenerated mock type for the BlockedPhonesRepository type
type MockBlockedPhonesRepository struct {
	mock.Mock
}

type MockBlockedPhonesRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlockedPhonesRepository) EXPECT() *MockBlockedPhonesRepository_Expecter {
	return &MockBlockedPhonesRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockBlockedPhonesRepository
func (_mock *MockBlockedPhonesRepository) Get(ctx context.Context) (*domain.BlockedPhones, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.BlockedPhones
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*domain.BlockedPhones, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *domain.BlockedPhones); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BlockedPhones)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockedPhonesRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockBlockedPhonesRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBlockedPhonesRepository_Expecter) Get(ctx interface{}) *MockBlockedPhonesRepository_Get_Call {
	return &MockBlockedPhonesRepository_Get_Call{Call: _e.mock.On("Get", ctx)}
}

func (_c *MockBlockedPhonesRepository_Get_Call) Run(run func(ctx context.Context)) *MockBlockedPhonesRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlockedPhonesRepository_Get_Call) Return(blockedPhones *domain.BlockedPhones, err error) *MockBlockedPhonesRepository_Get_Call {
	_c.Call.Return(blockedPhones, err)
	return _c
}

func (_c *MockBlockedPhonesRepository_Get_Call) RunAndReturn(run func(ctx context.Context) (*domain.BlockedPhones, error)) *MockBlockedPhonesRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockBlockedPhonesRepository
func (_mock *MockBlockedPhonesRepository) Save(ctx context.Context, phones *domain.BlockedPhones) error {
	ret := _mock.Called(ctx, phones)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.BlockedPhones) error); ok {
		r0 = returnFunc(ctx, phones)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlockedPhonesRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockBlockedPhonesRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - phones *domain.BlockedPhones
func (_e *MockBlockedPhonesRepository_Expecter) Save(ctx interface{}, phones interface{}) *MockBlockedPhonesRepository_Save_Call {
	return &MockBlockedPhonesRepository_Save_Call{Call: _e.mock.On("Save", ctx, phones)}
}

func (_c *MockBlockedPhonesRepository_Save_Call) Run(run func(ctx context.Context, phones *domain.BlockedPhones)) *MockBlockedPhonesRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.BlockedPhones
		if args[1] != nil {
			arg1 = args[1].(*domain.BlockedPhones)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlockedPhonesRepository_Save_Call) Return(err error) *MockBlockedPhonesRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlockedPhonesRepository_Save_Call) RunAndReturn(run func(ctx context.Context, phones *domain.BlockedPhones) error) *MockBlockedPhonesRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIntercessorPhonesRepository creates a new instance of MockIntercessorPhonesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIntercessorPhonesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIntercessorPhonesRepository {
	mock := &MockIntercessorPhonesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIntercessorPhonesRepository is an autogenerated mock type for the IntercessorPhonesRepository type
type MockIntercessorPhonesRepository struct {
	mock.Mock
}

type MockIntercessorPhonesRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIntercessorPhonesRepository) EXPECT() *MockIntercessorPhonesRepository_Expecter {
	return &MockIntercessorPhonesRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockIntercessorPhonesRepository
func (_mock *MockIntercessorPhonesRepository) Get(ctx context.Context) (*domain.IntercessorPhones, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.IntercessorPhones
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*domain.IntercessorPhones, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *domain.IntercessorPhones); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.IntercessorPhones)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIntercessorPhonesRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIntercessorPhonesRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIntercessorPhonesRepository_Expecter) Get(ctx interface{}) *MockIntercessorPhonesRepository_Get_Call {
	return &MockIntercessorPhonesRepository_Get_Call{Call: _e.mock.On("Get", ctx)}
}

func (_c *MockIntercessorPhonesRepository_Get_Call) Run(run func(ctx context.Context)) *MockIntercessorPhonesRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIntercessorPhonesRepository_Get_Call) Return(intercessorPhones *domain.IntercessorPhones, err error) *MockIntercessorPhonesRepository_Get_Call {
	_c.Call.Return(intercessorPhones, err)
	return _c
}

func (_c *MockIntercessorPhonesRepository_Get_Call) RunAndReturn(run func(ctx context.Context) (*domain.IntercessorPhones, error)) *MockIntercessorPhonesRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockIntercessorPhonesRepository
func (_mock *MockIntercessorPhonesRepository) Save(ctx context.Context, phones *domain.IntercessorPhones) error {
	ret := _mock.Called(ctx, phones)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.IntercessorPhones) error); ok {
		r0 = returnFunc(ctx, phones)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIntercessorPhonesRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockIntercessorPhonesRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - phones *domain.IntercessorPhones
func (_e *MockIntercessorPhonesRepository_Expecter) Save(ctx interface{}, phones interface{}) *MockIntercessorPhonesRepository_Save_Call {
	return &MockIntercessorPhonesRepository_Save_Call{Call: _e.mock.On("Save", ctx, phones)}
}

func (_c *MockIntercessorPhonesRepository_Save_Call) Run(run func(ctx context.Context, phones *domain.IntercessorPhones)) *MockIntercessorPhonesRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.IntercessorPhones
		if args[1] != nil {
			arg1 = args[1].(*domain.IntercessorPhones)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIntercessorPhonesRepository_Save_Call) Return(err error) *MockIntercessorPhonesRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIntercessorPhonesRepository_Save_Call) RunAndReturn(run func(ctx context.Context, phones *domain.IntercessorPhones) error) *MockIntercessorPhonesRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPrayerRepository creates a new instance of MockPrayerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrayerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrayerRepository {
	mock := &MockPrayerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPrayerRepository is an autogenerated mock type for the PrayerRepository type
type MockPrayerRepository struct {
	mock.Mock
}

type MockPrayerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrayerRepository) EXPECT() *MockPrayerRepository_Expecter {
	return &MockPrayerRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockPrayerRepository
func (_mock *MockPrayerRepository) Delete(ctx context.Context, key string, queued bool) error {
	ret := _mock.Called(ctx, key, queued)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, key, queued)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPrayerRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPrayerRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - queued bool
func (_e *MockPrayerRepository_Expecter) Delete(ctx interface{}, key interface{}, queued interface{}) *MockPrayerRepository_Delete_Call {
	return &MockPrayerRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, key, queued)}
}

func (_c *MockPrayerRepository_Delete_Call) Run(run func(ctx context.Context, key string, queued bool)) *MockPrayerRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPrayerRepository_Delete_Call) Return(err error) *MockPrayerRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPrayerRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, key string, queued bool) error) *MockPrayerRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockPrayerRepository
func (_mock *MockPrayerRepository) Exists(ctx context.Context, phone string) (bool, error) {
	ret := _mock.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, phone)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, phone)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, phone)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPrayerRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockPrayerRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
func (_e *MockPrayerRepository_Expecter) Exists(ctx interface{}, phone interface{}) *MockPrayerRepository_Exists_Call {
	return &MockPrayerRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, phone)}
}

func (_c *MockPrayerRepository_Exists_Call) Run(run func(ctx context.Context, phone string)) *MockPrayerRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPrayerRepository_Exists_Call) Return(b bool, err error) *MockPrayerRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockPrayerRepository_Exists_Call) RunAndReturn(run func(ctx context.Context, phone string) (bool, error)) *MockPrayerRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockPrayerRepository
func (_mock *MockPrayerRepository) Get(ctx context.Context, key string, queued bool) (*domain.Prayer, error) {
	ret := _mock.Called(ctx, key, queued)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Prayer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) (*domain.Prayer, error)); ok {
		return returnFunc(ctx, key, queued)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) *domain.Prayer); ok {
		r0 = returnFunc(ctx, key, queued)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Prayer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = returnFunc(ctx, key, queued)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPrayerRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPrayerRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - queued bool
func (_e *MockPrayerRepository_Expecter) Get(ctx interface{}, key interface{}, queued interface{}) *MockPrayerRepository_Get_Call {
	return &MockPrayerRepository_Get_Call{Call: _e.mock.On("Get", ctx, key, queued)}
}

func (_c *MockPrayerRepository_Get_Call) Run(run func(ctx context.Context, key string, queued bool)) *MockPrayerRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPrayerRepository_Get_Call) Return(prayer *domain.Prayer, err error) *MockPrayerRepository_Get_Call {
	_c.Call.Return(prayer, err)
	return _c
}

func (_c *MockPrayerRepository_Get_Call) RunAndReturn(run func(ctx context.Context, key string, queued bool) (*domain.Prayer, error)) *MockPrayerRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockPrayerRepository
func (_mock *MockPrayerRepository) GetAll(ctx context.Context, queued bool) ([]domain.Prayer, error) {
	ret := _mock.Called(ctx, queued)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Prayer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) ([]domain.Prayer, error)); ok {
		return returnFunc(ctx, queued)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) []domain.Prayer); ok {
		r0 = returnFunc(ctx, queued)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Prayer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = returnFunc(ctx, queued)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPrayerRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockPrayerRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - queued bool
func (_e *MockPrayerRepository_Expecter) GetAll(ctx interface{}, queued interface{}) *MockPrayerRepository_GetAll_Call {
	return &MockPrayerRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx, queued)}
}

func (_c *MockPrayerRepository_GetAll_Call) Run(run func(ctx context.Context, queued bool)) *MockPrayerRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPrayerRepository_GetAll_Call) Return(prayers []domain.Prayer, err error) *MockPrayerRepository_GetAll_Call {
	_c.Call.Return(prayers, err)
	return _c
}

func (_c *MockPrayerRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context, queued bool) ([]domain.Prayer, error)) *MockPrayerRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockPrayerRepository
func (_mock *MockPrayerRepository) Save(ctx context.Context, prayer *domain.Prayer, queued bool) error {
	ret := _mock.Called(ctx, prayer, queued)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Prayer, bool) error); ok {
		r0 = returnFunc(ctx, prayer, queued)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPrayerRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockPrayerRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - prayer *domain.Prayer
//   - queued bool
func (_e *MockPrayerRepository_Expecter) Save(ctx interface{}, prayer interface{}, queued interface{}) *MockPrayerRepository_Save_Call {
	return &MockPrayerRepository_Save_Call{Call: _e.mock.On("Save", ctx, prayer, queued)}
}

func (_c *MockPrayerRepository_Save_Call) Run(run func(ctx context.Context, prayer *domain.Prayer, queued bool)) *MockPrayerRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Prayer
		if args[1] != nil {
			arg1 = args[1].(*domain.Prayer)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPrayerRepository_Save_Call) Return(err error) *MockPrayerRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPrayerRepository_Save_Call) RunAndReturn(run func(ctx context.Context, prayer *domain.Prayer, queued bool) error) *MockPrayerRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
