// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMessageSender creates a new instance of MockMessageSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageSender {
	mock := &MockMessageSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessageSender is an autogenerated mock type for the MessageSender type
type MockMessageSender struct {
	mock.Mock
}

type MockMessageSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageSender) EXPECT() *MockMessageSender_Expecter {
	return &MockMessageSender_Expecter{mock: &_m.Mock}
}

// SendMessage provides a mock function for the type MockMessageSender
func (_mock *MockMessageSender) SendMessage(ctx context.Context, to string, body string) error {
	ret := _mock.Called(ctx, to, body)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, to, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessageSender_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockMessageSender_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - body string
func (_e *MockMessageSender_Expecter) SendMessage(ctx interface{}, to interface{}, body interface{}) *MockMessageSender_SendMessage_Call {
	return &MockMessageSender_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, to, body)}
}

func (_c *MockMessageSender_SendMessage_Call) Run(run func(ctx context.Context, to string, body string)) *MockMessageSender_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMessageSender_SendMessage_Call) Return(err error) *MockMessageSender_SendMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessageSender_SendMessage_Call) RunAndReturn(run func(ctx context.Context, to string, body string) error) *MockMessageSender_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}
