version = 0.1
[default.deploy.parameters]
stack_name = "prayertexter"
resolve_s3 = true
s3_prefix = "prayertexter"
region = "us-west-1"
profile = "AdministratorAccess-681271545794"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"