version = 0.1
[default.deploy.parameters]
stack_name = "statecontroller"
resolve_s3 = true
s3_prefix = "statecontroller"
region = "us-west-1"
profile = "AdministratorAccess-681271545794"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"