name: Lint cloudFormation templates
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cloudformation-linter:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          pwd
          ls -lah
          cfn-lint --version
          cfn-lint -t deploy/db/template.yaml
          cfn-lint -t deploy/prayertexter/template.yaml
          cfn-lint -t deploy/stateresolver/template.yaml